### ISSUE TITLE
Gestione segnalazioni

### ISSUE THREAD

**Issue by Lollerix** [Databasers/BachecaUnisa#1]
Serve decidere come vogliamo gestire le segnalazioni e in che modo il manager interagisce con il database e il browser

**Comment by MarcoCalenda14** [comment]
Una segnalazione e' un'entità che e' collegata con una foreign key o all'id di un annuncio o all'id di una recensione. Quando un annuncio o una recensione e' segnalata il contatore delle proprie segnalazioni (int nell'annuncio o segnalazione) sale di uno. Ogni segnalazione ha un motivo obbligatorio ed una descrizione facoltativa. Un utente può segnalare un annuncio (non il proprio) oppure una recensione (solo relativa al suo profilo). Per quanto riguarda il gestore egli può visualizzare tutte le segnalazioni relative a recensioni e annunci ed inoltre può rimuoverle.
