### ISSUE TITLE
Pagine Web mancanti

### ISSUE THREAD

**Issue by FDema98** [Databasers/BachecaUnisa#10]
I nostri riferimenti restano i mock-up presenti nel RAD.
In particolare mancano alcune pagine:
- Mock-up 6 - Visualizza profilo altro utente
- Mock-up 8 - Tabella "i miei annunci" con pulsanti per visualizzarli ed elimiinarli
- Mock-up 15 - Tabella "cerca annuncio"
- Mock-up 16 -  Tabella "cerca utente"
- Mock-up 17 - Visualizza segnalazioni annunci
- Mock-up 15 - Visualizza segnalazioni recensioni

**Comment by mystero1** [comment]
M6 è uguale al M5 che c'è, basta aggiungere un pulsante
M8 deve essere generato dinamicamente
M15-16-17 sono la stessa pagina e anche quella deve essere generata dinamicamente

Posso provare a mettermele a fare

**Comment by mystero1** [comment]
Ora ci sono tutte
