### ISSUE TITLE
Ricerca annunci

### ISSUE THREAD

**Issue by Lollerix** [Databasers/BachecaUnisa#4]
Attualmente il metodo nel manager prende:
`public void cercaAnnuncio(String dipartimento, String titolo, String descrizione, String tipologia)`
Come facciamo a creare una roba per far funzionare sti filtri? Come facciamo a sapere quali di questi sono attivi?

**Comment by FDema98** [comment]
Se facciamo vari doRetriveBy*** come sta scritto in UtenteManager?

**Comment by Lollerix** [comment]
Si può fare, e sarà problema della servlet chiedere quale vuole
