### ISSUE TITLE
Tabella Recensione

### ISSUE THREAD

**Issue by Lollerix** [Databasers/BachecaUnisa#5]
La tabella recensione ha queste colonne:

- Descrizione

- Mittente

- Annuncio_ID

- ID

- Destinatario

- Valutazione

A che serve annuncio_ID?

**Comment by FDema98** [comment]
Non serve perché la recensione si riferisce all'utente e non ad un annuncio

**Comment by Lollerix** [comment]
> Non serve perché la recensione si riferisce all'utente e non ad un annuncio

E sono d'accordo con te, la droppo quindi?

**Comment by MarcoCalenda14** [comment]
Droppi lei
