### ISSUE TITLE
Segnalazione

### ISSUE THREAD

**Issue by Lollerix** [Databasers/BachecaUnisa#6]
La precondizione della creazione di una segnalazione ponetela dentro la servlet stessa. Supponendo essa abbia un riferimento al segnalabile, esso ha un metodo per dare il numero di segnalazioni, a quel punto bisogna per forza controllarne la classe e mandare alla servlet o manager corretta la richiesta di rimozione

**Comment by Lollerix** [comment]
Segnalazione è stata revampata. Ecco come funziona ora;
La classe contiene l'ID(int), la motivazione(int), la descrizione(string) , recensione(int), annuncio(int).
Recensione e annuncio dovranno essere mutualmente esclusivi. Più tardi ne modifico i setter in modo da annullare l'altro. Uno dei campi vale "null" quando è pari a -1, essendo un valore non esistente nel db.
isTipologia ora è un metodo che vede quale dei due campi è null invece che una inutile variabile.

**Comment by FDema98** [comment]
"Uno dei campi vale "null" quando è pari a -1, essendo un valore non esistente nel db."
Dunque il valore non nullo a cosa sarà uguale? All'id dell'oggetto di riferimento?

**Comment by Lollerix** [comment]
> Dunque il valore non nullo a cosa sarà uguale? All'id dell'oggetto di riferimento?

Esattamente
