### ISSUE TITLE
Modifica Annuncio

### ISSUE THREAD

**Issue by FDema98** [Databasers/BachecaUnisa#9]
Ragazzi bisogna decidere per bene cosa deve fare Modifica Annuncio: nella servlet prende come parametri l'id come riferimento all'annuncio, poi il titolo e la descrizione da aggiornare (dunque modifica annuncio nella servlet permette di modificare solo titolo e descrizione). Mentre in AnnuncioManager si permette di modificare tutto.
Secondo me bisogna limitare il modifica annuncio solo ad una piccola modifica (come per titolo e descrizione), nel caso l'utente voglia completamente modificarlo dovrebbe eliminarlo e crearne uno nuovo

**Comment by Lollerix** [comment]
E tutto quello che hai detto è già quello che il metodo fa

**Comment by MarcoCalenda14** [comment]
Chiariamo: 

NELLA SERVLET:
private void modificaAnnuncio(int id, String titolo, String descrizione) {
  ====
#1 RECUPERO ANNUNCIO TRAMITE ID
#2 SETTO I NUOVI TITOLO E DESCRIZIONE
#3 CHIAMO MODIFICA ANNUNCIO DELL MANAGER PASSANDO ANNUNCIO MODIFICATO
  ====
  }

NEL MANAGER:
public void modificaAnnuncio(Annuncio annuncio) throws SQLException {
   1# CREO CONNESSIONE E STATEMENT
    try { 
   2# RIEMPIO PREP STATEMENT CON I GETTER DELL'ANNUNCIO PASSATO 
    } finally {
      
   3# CHIUDO TUTTO

**Comment by Lollerix** [comment]
> Chiariamo:
> 
> NELLA SERVLET:
> private void modificaAnnuncio(int id, String titolo, String descrizione) {
> #1 RECUPERO ANNUNCIO TRAMITE ID
> #2 SETTO I NUOVI TITOLO E DESCRIZIONE
> #3 CHIAMO MODIFICA ANNUNCIO DELL MANAGER PASSANDO ANNUNCIO MODIFICATO
> 
> NEL MANAGER:
> public void modificaAnnuncio(Annuncio annuncio) throws SQLException {
> #1 CREO CONNESSIONE E STATEMENT
> #2 RIEMPIO PREP STATEMENT CON I GETTER DELL'ANNUNCIO PASSATO
> #3 CHIUDO TUTTO

Ye
